# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: minknow_api/rpc_options.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto
