# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: minknow_api/analysis_workflows.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    AsyncIterator,
    Dict,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class ProxyRequestMethod(betterproto.Enum):
    GET = 0
    POST = 1
    PUT = 2
    DELETE = 3


@dataclass(eq=False, repr=False)
class ProxyRequest(betterproto.Message):
    api: str = betterproto.string_field(1)
    """
    with parameters but without the endpoint e.g.  for API /workflows/{id}/start:
     "/workflows/ae088129-8767-460f-8795-7c04771dc42f/start"
     "/workflows/epi2me-labs/wf-alignment/v1.2.8/start"
    """

    method: "ProxyRequestMethod" = betterproto.enum_field(2)
    headers: Dict[str, str] = betterproto.map_field(
        4, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    request_body: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ProxyResponse(betterproto.Message):
    status_code: int = betterproto.uint32_field(1)
    response_body: str = betterproto.string_field(2)


class AnalysisWorkflowsServiceStub(betterproto.ServiceStub):
    async def proxy(
        self,
        proxy_request: "ProxyRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> AsyncIterator[ProxyResponse]:
        async for response in self._unary_stream(
            "/minknow_api.analysis_workflows.AnalysisWorkflowsService/proxy",
            proxy_request,
            ProxyResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response


class AnalysisWorkflowsServiceBase(ServiceBase):

    async def proxy(
        self, proxy_request: "ProxyRequest"
    ) -> AsyncIterator[ProxyResponse]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield ProxyResponse()

    async def __rpc_proxy(
        self, stream: "grpclib.server.Stream[ProxyRequest, ProxyResponse]"
    ) -> None:
        request = await stream.recv_message()
        await self._call_rpc_handler_server_stream(
            self.proxy,
            stream,
            request,
        )

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/minknow_api.analysis_workflows.AnalysisWorkflowsService/proxy": grpclib.const.Handler(
                self.__rpc_proxy,
                grpclib.const.Cardinality.UNARY_STREAM,
                ProxyRequest,
                ProxyResponse,
            ),
        }
